### PR TITLE
Clear flash CMP bit, add new SR size

### PR DESCRIPTION
**Pull request by mokap13**
Problem: MCU bk7238, firmware changed bit CMP to 1 and i can't program memory from bk7231tools. 

I added new SR size(for my flash) and CMP zero init, it's work for me now.

### CODE REVIEW

**Comment by kuba2k2** [comment]
Thanks for the fix. Could you explain in which scenarios does it not work before applying this fix?

I'm trying to understand if this PR will fix an unprotection issue we've been seeing for a long time, where writing wouldn't work if the device was in a boot loop.

**Comment by mokap13** [comment]
bk7231tools can't erase memory if CMP bit was previously set to 1.

```
bk7231tools write_flash ~/firmware -B -d /dev/tty.usbserial-B003BKOO -b 2000000
Unknown bootloader CRC - 0x6BEB0924 - please report this on GitHub issues!
Reading 4k page at 0x011000 (0.00%)
BK72xx connected - protocol: FULL, chip: BK7238, bootloader: None, chip ID: 0x7238, boot version: None
Connected! Chip info: BK7238 / Flash ID: 85 20 15 / Flash size: 0x200000 / Protocol: FULL
Writing 1314315 bytes to 0x0
Trying to unprotect flash memory...
Erasing and writing at 0x0 (0.00%)
 - Checking block pre-erase @ 0x0
 - Trying to erase block @ 0x0
 - Checking block post-erase @ 0x0
Erasing failure @ 0x0 (Erase failed - flash protected; found non-0xFF bytes @ 0x0), retrying (attempt 0)
 - Checking block pre-erase @ 0x0
 - Trying to erase block @ 0x0
 - Checking block post-erase @ 0x0
Erasing failure @ 0x0 (Erase failed - flash protected; found non-0xFF bytes @ 0x0), retrying (attempt 1)
 - Checking block pre-erase @ 0x0
 - Trying to erase block @ 0x0
 - Checking block post-erase @ 0x0
Erasing failure @ 0x0 (Erase failed - flash protected; found non-0xFF bytes @ 0x0), retrying (attempt 2)
 - Checking block pre-erase @ 0x0
 - Trying to erase block @ 0x0
 - Checking block post-erase @ 0x0
Erasing failure @ 0x0 (Erase failed - flash protected; found non-0xFF bytes @ 0x0), retrying (attempt 3)
Traceback (most recent call last):
  File "/Users/user/projects/py-scripts/.venv/bin/bk7231tools", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/Users/user/projects/py-scripts/.venv/lib/python3.13/site-packages/bk7231tools/__main__.py", line 626, in cli
    args.handler(device, args)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/user/projects/py-scripts/.venv/lib/python3.13/site-packages/bk7231tools/__main__.py", line 470, in write_flash
    for _ in device.program_flash(
             ~~~~~~~~~~~~~~~~~~~~^
        io=fs,
        ^^^^^^
    ...<3 lines>...
        dry_run=False,
        ^^^^^^^^^^^^^^
    ):
    ^
  File "/Users/user/projects/py-scripts/.venv/lib/python3.13/site-packages/bk7231tools/serial/cmd_hl_flash.py", line 187, in program_flash
    self.flash_erase_block(
    ~~~~~~~~~~~~~~~~~~~~~~^
        addr,
        ^^^^^
        EraseSize.SECTOR_4K,
        ^^^^^^^^^^^^^^^^^^^^
        dry_run=dry_run,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/user/projects/py-scripts/.venv/lib/python3.13/site-packages/bk7231tools/serial/cmd_ll_flash.py", line 229, in flash_erase_block
    do_erase_verify()
    ~~~~~~~~~~~~~~~^^
  File "/Users/user/projects/py-scripts/.venv/lib/python3.13/site-packages/bk7231tools/serial/cmd_ll_flash.py", line 209, in do_erase_verify
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Erase failed - flash protected; found non-0xFF bytes @ 0x0
```

**Comment by kuba2k2** [comment]
Thanks. Could you also attach a stock firmware dump from the device? It could help with further support for this chip.

**Comment by arikon** [comment]
@kuba2k2 Bootloader dump is the same as here: https://github.com/tuya-cloudcutter/bk7231tools/issues/23#issuecomment-2059849794

**Pull request merged**
